// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: internal/int32/proto/testint32_50.proto

package benchmarkpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestInt32_50 struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	F00           int32                  `protobuf:"varint,1,opt,name=f00,proto3" json:"f00,omitempty"`
	F01           int32                  `protobuf:"varint,2,opt,name=f01,proto3" json:"f01,omitempty"`
	F02           int32                  `protobuf:"varint,3,opt,name=f02,proto3" json:"f02,omitempty"`
	F03           int32                  `protobuf:"varint,4,opt,name=f03,proto3" json:"f03,omitempty"`
	F04           int32                  `protobuf:"varint,5,opt,name=f04,proto3" json:"f04,omitempty"`
	F05           int32                  `protobuf:"varint,6,opt,name=f05,proto3" json:"f05,omitempty"`
	F06           int32                  `protobuf:"varint,7,opt,name=f06,proto3" json:"f06,omitempty"`
	F07           int32                  `protobuf:"varint,8,opt,name=f07,proto3" json:"f07,omitempty"`
	F08           int32                  `protobuf:"varint,9,opt,name=f08,proto3" json:"f08,omitempty"`
	F09           int32                  `protobuf:"varint,10,opt,name=f09,proto3" json:"f09,omitempty"`
	F10           int32                  `protobuf:"varint,11,opt,name=f10,proto3" json:"f10,omitempty"`
	F11           int32                  `protobuf:"varint,12,opt,name=f11,proto3" json:"f11,omitempty"`
	F12           int32                  `protobuf:"varint,13,opt,name=f12,proto3" json:"f12,omitempty"`
	F13           int32                  `protobuf:"varint,14,opt,name=f13,proto3" json:"f13,omitempty"`
	F14           int32                  `protobuf:"varint,15,opt,name=f14,proto3" json:"f14,omitempty"`
	F15           int32                  `protobuf:"varint,16,opt,name=f15,proto3" json:"f15,omitempty"`
	F16           int32                  `protobuf:"varint,17,opt,name=f16,proto3" json:"f16,omitempty"`
	F17           int32                  `protobuf:"varint,18,opt,name=f17,proto3" json:"f17,omitempty"`
	F18           int32                  `protobuf:"varint,19,opt,name=f18,proto3" json:"f18,omitempty"`
	F19           int32                  `protobuf:"varint,20,opt,name=f19,proto3" json:"f19,omitempty"`
	F20           int32                  `protobuf:"varint,21,opt,name=f20,proto3" json:"f20,omitempty"`
	F21           int32                  `protobuf:"varint,22,opt,name=f21,proto3" json:"f21,omitempty"`
	F22           int32                  `protobuf:"varint,23,opt,name=f22,proto3" json:"f22,omitempty"`
	F23           int32                  `protobuf:"varint,24,opt,name=f23,proto3" json:"f23,omitempty"`
	F24           int32                  `protobuf:"varint,25,opt,name=f24,proto3" json:"f24,omitempty"`
	F25           int32                  `protobuf:"varint,26,opt,name=f25,proto3" json:"f25,omitempty"`
	F26           int32                  `protobuf:"varint,27,opt,name=f26,proto3" json:"f26,omitempty"`
	F27           int32                  `protobuf:"varint,28,opt,name=f27,proto3" json:"f27,omitempty"`
	F28           int32                  `protobuf:"varint,29,opt,name=f28,proto3" json:"f28,omitempty"`
	F29           int32                  `protobuf:"varint,30,opt,name=f29,proto3" json:"f29,omitempty"`
	F30           int32                  `protobuf:"varint,31,opt,name=f30,proto3" json:"f30,omitempty"`
	F31           int32                  `protobuf:"varint,32,opt,name=f31,proto3" json:"f31,omitempty"`
	F32           int32                  `protobuf:"varint,33,opt,name=f32,proto3" json:"f32,omitempty"`
	F33           int32                  `protobuf:"varint,34,opt,name=f33,proto3" json:"f33,omitempty"`
	F34           int32                  `protobuf:"varint,35,opt,name=f34,proto3" json:"f34,omitempty"`
	F35           int32                  `protobuf:"varint,36,opt,name=f35,proto3" json:"f35,omitempty"`
	F36           int32                  `protobuf:"varint,37,opt,name=f36,proto3" json:"f36,omitempty"`
	F37           int32                  `protobuf:"varint,38,opt,name=f37,proto3" json:"f37,omitempty"`
	F38           int32                  `protobuf:"varint,39,opt,name=f38,proto3" json:"f38,omitempty"`
	F39           int32                  `protobuf:"varint,40,opt,name=f39,proto3" json:"f39,omitempty"`
	F40           int32                  `protobuf:"varint,41,opt,name=f40,proto3" json:"f40,omitempty"`
	F41           int32                  `protobuf:"varint,42,opt,name=f41,proto3" json:"f41,omitempty"`
	F42           int32                  `protobuf:"varint,43,opt,name=f42,proto3" json:"f42,omitempty"`
	F43           int32                  `protobuf:"varint,44,opt,name=f43,proto3" json:"f43,omitempty"`
	F44           int32                  `protobuf:"varint,45,opt,name=f44,proto3" json:"f44,omitempty"`
	F45           int32                  `protobuf:"varint,46,opt,name=f45,proto3" json:"f45,omitempty"`
	F46           int32                  `protobuf:"varint,47,opt,name=f46,proto3" json:"f46,omitempty"`
	F47           int32                  `protobuf:"varint,48,opt,name=f47,proto3" json:"f47,omitempty"`
	F48           int32                  `protobuf:"varint,49,opt,name=f48,proto3" json:"f48,omitempty"`
	F49           int32                  `protobuf:"varint,50,opt,name=f49,proto3" json:"f49,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestInt32_50) Reset() {
	*x = TestInt32_50{}
	mi := &file_internal_int32_proto_testint32_50_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestInt32_50) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestInt32_50) ProtoMessage() {}

func (x *TestInt32_50) ProtoReflect() protoreflect.Message {
	mi := &file_internal_int32_proto_testint32_50_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestInt32_50.ProtoReflect.Descriptor instead.
func (*TestInt32_50) Descriptor() ([]byte, []int) {
	return file_internal_int32_proto_testint32_50_proto_rawDescGZIP(), []int{0}
}

func (x *TestInt32_50) GetF00() int32 {
	if x != nil {
		return x.F00
	}
	return 0
}

func (x *TestInt32_50) GetF01() int32 {
	if x != nil {
		return x.F01
	}
	return 0
}

func (x *TestInt32_50) GetF02() int32 {
	if x != nil {
		return x.F02
	}
	return 0
}

func (x *TestInt32_50) GetF03() int32 {
	if x != nil {
		return x.F03
	}
	return 0
}

func (x *TestInt32_50) GetF04() int32 {
	if x != nil {
		return x.F04
	}
	return 0
}

func (x *TestInt32_50) GetF05() int32 {
	if x != nil {
		return x.F05
	}
	return 0
}

func (x *TestInt32_50) GetF06() int32 {
	if x != nil {
		return x.F06
	}
	return 0
}

func (x *TestInt32_50) GetF07() int32 {
	if x != nil {
		return x.F07
	}
	return 0
}

func (x *TestInt32_50) GetF08() int32 {
	if x != nil {
		return x.F08
	}
	return 0
}

func (x *TestInt32_50) GetF09() int32 {
	if x != nil {
		return x.F09
	}
	return 0
}

func (x *TestInt32_50) GetF10() int32 {
	if x != nil {
		return x.F10
	}
	return 0
}

func (x *TestInt32_50) GetF11() int32 {
	if x != nil {
		return x.F11
	}
	return 0
}

func (x *TestInt32_50) GetF12() int32 {
	if x != nil {
		return x.F12
	}
	return 0
}

func (x *TestInt32_50) GetF13() int32 {
	if x != nil {
		return x.F13
	}
	return 0
}

func (x *TestInt32_50) GetF14() int32 {
	if x != nil {
		return x.F14
	}
	return 0
}

func (x *TestInt32_50) GetF15() int32 {
	if x != nil {
		return x.F15
	}
	return 0
}

func (x *TestInt32_50) GetF16() int32 {
	if x != nil {
		return x.F16
	}
	return 0
}

func (x *TestInt32_50) GetF17() int32 {
	if x != nil {
		return x.F17
	}
	return 0
}

func (x *TestInt32_50) GetF18() int32 {
	if x != nil {
		return x.F18
	}
	return 0
}

func (x *TestInt32_50) GetF19() int32 {
	if x != nil {
		return x.F19
	}
	return 0
}

func (x *TestInt32_50) GetF20() int32 {
	if x != nil {
		return x.F20
	}
	return 0
}

func (x *TestInt32_50) GetF21() int32 {
	if x != nil {
		return x.F21
	}
	return 0
}

func (x *TestInt32_50) GetF22() int32 {
	if x != nil {
		return x.F22
	}
	return 0
}

func (x *TestInt32_50) GetF23() int32 {
	if x != nil {
		return x.F23
	}
	return 0
}

func (x *TestInt32_50) GetF24() int32 {
	if x != nil {
		return x.F24
	}
	return 0
}

func (x *TestInt32_50) GetF25() int32 {
	if x != nil {
		return x.F25
	}
	return 0
}

func (x *TestInt32_50) GetF26() int32 {
	if x != nil {
		return x.F26
	}
	return 0
}

func (x *TestInt32_50) GetF27() int32 {
	if x != nil {
		return x.F27
	}
	return 0
}

func (x *TestInt32_50) GetF28() int32 {
	if x != nil {
		return x.F28
	}
	return 0
}

func (x *TestInt32_50) GetF29() int32 {
	if x != nil {
		return x.F29
	}
	return 0
}

func (x *TestInt32_50) GetF30() int32 {
	if x != nil {
		return x.F30
	}
	return 0
}

func (x *TestInt32_50) GetF31() int32 {
	if x != nil {
		return x.F31
	}
	return 0
}

func (x *TestInt32_50) GetF32() int32 {
	if x != nil {
		return x.F32
	}
	return 0
}

func (x *TestInt32_50) GetF33() int32 {
	if x != nil {
		return x.F33
	}
	return 0
}

func (x *TestInt32_50) GetF34() int32 {
	if x != nil {
		return x.F34
	}
	return 0
}

func (x *TestInt32_50) GetF35() int32 {
	if x != nil {
		return x.F35
	}
	return 0
}

func (x *TestInt32_50) GetF36() int32 {
	if x != nil {
		return x.F36
	}
	return 0
}

func (x *TestInt32_50) GetF37() int32 {
	if x != nil {
		return x.F37
	}
	return 0
}

func (x *TestInt32_50) GetF38() int32 {
	if x != nil {
		return x.F38
	}
	return 0
}

func (x *TestInt32_50) GetF39() int32 {
	if x != nil {
		return x.F39
	}
	return 0
}

func (x *TestInt32_50) GetF40() int32 {
	if x != nil {
		return x.F40
	}
	return 0
}

func (x *TestInt32_50) GetF41() int32 {
	if x != nil {
		return x.F41
	}
	return 0
}

func (x *TestInt32_50) GetF42() int32 {
	if x != nil {
		return x.F42
	}
	return 0
}

func (x *TestInt32_50) GetF43() int32 {
	if x != nil {
		return x.F43
	}
	return 0
}

func (x *TestInt32_50) GetF44() int32 {
	if x != nil {
		return x.F44
	}
	return 0
}

func (x *TestInt32_50) GetF45() int32 {
	if x != nil {
		return x.F45
	}
	return 0
}

func (x *TestInt32_50) GetF46() int32 {
	if x != nil {
		return x.F46
	}
	return 0
}

func (x *TestInt32_50) GetF47() int32 {
	if x != nil {
		return x.F47
	}
	return 0
}

func (x *TestInt32_50) GetF48() int32 {
	if x != nil {
		return x.F48
	}
	return 0
}

func (x *TestInt32_50) GetF49() int32 {
	if x != nil {
		return x.F49
	}
	return 0
}

var File_internal_int32_proto_testint32_50_proto protoreflect.FileDescriptor

const file_internal_int32_proto_testint32_50_proto_rawDesc = "" +
	"\n" +
	"'internal/int32/proto/testint32_50.proto\x12\vbenchmarkpb\"\x92\a\n" +
	"\fTestInt32_50\x12\x10\n" +
	"\x03f00\x18\x01 \x01(\x05R\x03f00\x12\x10\n" +
	"\x03f01\x18\x02 \x01(\x05R\x03f01\x12\x10\n" +
	"\x03f02\x18\x03 \x01(\x05R\x03f02\x12\x10\n" +
	"\x03f03\x18\x04 \x01(\x05R\x03f03\x12\x10\n" +
	"\x03f04\x18\x05 \x01(\x05R\x03f04\x12\x10\n" +
	"\x03f05\x18\x06 \x01(\x05R\x03f05\x12\x10\n" +
	"\x03f06\x18\a \x01(\x05R\x03f06\x12\x10\n" +
	"\x03f07\x18\b \x01(\x05R\x03f07\x12\x10\n" +
	"\x03f08\x18\t \x01(\x05R\x03f08\x12\x10\n" +
	"\x03f09\x18\n" +
	" \x01(\x05R\x03f09\x12\x10\n" +
	"\x03f10\x18\v \x01(\x05R\x03f10\x12\x10\n" +
	"\x03f11\x18\f \x01(\x05R\x03f11\x12\x10\n" +
	"\x03f12\x18\r \x01(\x05R\x03f12\x12\x10\n" +
	"\x03f13\x18\x0e \x01(\x05R\x03f13\x12\x10\n" +
	"\x03f14\x18\x0f \x01(\x05R\x03f14\x12\x10\n" +
	"\x03f15\x18\x10 \x01(\x05R\x03f15\x12\x10\n" +
	"\x03f16\x18\x11 \x01(\x05R\x03f16\x12\x10\n" +
	"\x03f17\x18\x12 \x01(\x05R\x03f17\x12\x10\n" +
	"\x03f18\x18\x13 \x01(\x05R\x03f18\x12\x10\n" +
	"\x03f19\x18\x14 \x01(\x05R\x03f19\x12\x10\n" +
	"\x03f20\x18\x15 \x01(\x05R\x03f20\x12\x10\n" +
	"\x03f21\x18\x16 \x01(\x05R\x03f21\x12\x10\n" +
	"\x03f22\x18\x17 \x01(\x05R\x03f22\x12\x10\n" +
	"\x03f23\x18\x18 \x01(\x05R\x03f23\x12\x10\n" +
	"\x03f24\x18\x19 \x01(\x05R\x03f24\x12\x10\n" +
	"\x03f25\x18\x1a \x01(\x05R\x03f25\x12\x10\n" +
	"\x03f26\x18\x1b \x01(\x05R\x03f26\x12\x10\n" +
	"\x03f27\x18\x1c \x01(\x05R\x03f27\x12\x10\n" +
	"\x03f28\x18\x1d \x01(\x05R\x03f28\x12\x10\n" +
	"\x03f29\x18\x1e \x01(\x05R\x03f29\x12\x10\n" +
	"\x03f30\x18\x1f \x01(\x05R\x03f30\x12\x10\n" +
	"\x03f31\x18  \x01(\x05R\x03f31\x12\x10\n" +
	"\x03f32\x18! \x01(\x05R\x03f32\x12\x10\n" +
	"\x03f33\x18\" \x01(\x05R\x03f33\x12\x10\n" +
	"\x03f34\x18# \x01(\x05R\x03f34\x12\x10\n" +
	"\x03f35\x18$ \x01(\x05R\x03f35\x12\x10\n" +
	"\x03f36\x18% \x01(\x05R\x03f36\x12\x10\n" +
	"\x03f37\x18& \x01(\x05R\x03f37\x12\x10\n" +
	"\x03f38\x18' \x01(\x05R\x03f38\x12\x10\n" +
	"\x03f39\x18( \x01(\x05R\x03f39\x12\x10\n" +
	"\x03f40\x18) \x01(\x05R\x03f40\x12\x10\n" +
	"\x03f41\x18* \x01(\x05R\x03f41\x12\x10\n" +
	"\x03f42\x18+ \x01(\x05R\x03f42\x12\x10\n" +
	"\x03f43\x18, \x01(\x05R\x03f43\x12\x10\n" +
	"\x03f44\x18- \x01(\x05R\x03f44\x12\x10\n" +
	"\x03f45\x18. \x01(\x05R\x03f45\x12\x10\n" +
	"\x03f46\x18/ \x01(\x05R\x03f46\x12\x10\n" +
	"\x03f47\x180 \x01(\x05R\x03f47\x12\x10\n" +
	"\x03f48\x181 \x01(\x05R\x03f48\x12\x10\n" +
	"\x03f49\x182 \x01(\x05R\x03f49B\"Z internal/int32/proto;benchmarkpbb\x06proto3"

var (
	file_internal_int32_proto_testint32_50_proto_rawDescOnce sync.Once
	file_internal_int32_proto_testint32_50_proto_rawDescData []byte
)

func file_internal_int32_proto_testint32_50_proto_rawDescGZIP() []byte {
	file_internal_int32_proto_testint32_50_proto_rawDescOnce.Do(func() {
		file_internal_int32_proto_testint32_50_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_int32_proto_testint32_50_proto_rawDesc), len(file_internal_int32_proto_testint32_50_proto_rawDesc)))
	})
	return file_internal_int32_proto_testint32_50_proto_rawDescData
}

var file_internal_int32_proto_testint32_50_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_int32_proto_testint32_50_proto_goTypes = []any{
	(*TestInt32_50)(nil), // 0: benchmarkpb.TestInt32_50
}
var file_internal_int32_proto_testint32_50_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_int32_proto_testint32_50_proto_init() }
func file_internal_int32_proto_testint32_50_proto_init() {
	if File_internal_int32_proto_testint32_50_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_int32_proto_testint32_50_proto_rawDesc), len(file_internal_int32_proto_testint32_50_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_int32_proto_testint32_50_proto_goTypes,
		DependencyIndexes: file_internal_int32_proto_testint32_50_proto_depIdxs,
		MessageInfos:      file_internal_int32_proto_testint32_50_proto_msgTypes,
	}.Build()
	File_internal_int32_proto_testint32_50_proto = out.File
	file_internal_int32_proto_testint32_50_proto_goTypes = nil
	file_internal_int32_proto_testint32_50_proto_depIdxs = nil
}
